import { z } from "zod";
import { sourceKindSchema } from "@/schemas/source";
import { SECURITY_RULE, subjectInputSchema } from "@/prompts/shared";
export const purpose = "research_plan" as const;
export const system = `Plan bounded public-source research for this subject. ${SECURITY_RULE}
Produce exactly queryBudget queries, using querySeeds as starting points and adapting them only with facts supplied in the subject. Write short executable web searches, not research instructions or long bags of keywords. Quote the full name and organization to reduce namesake matches. Use the person plus organization for relationship and role searches; include person-only career searches and organization-focused business searches. Cover: current role/team, career history, original interviews, company product/business model, funding/announcements, public metrics, regulatory records, and current-role changes/corrections. Do not infer a sector, jurisdiction, previous employer, founder status, funding round, or regulator from the name. Add those terms only when supported by supplied evidence. Use domain restrictions only for known authoritative domains, never guessed company domains. Do not constrain every query to one publisher; seek independent coverage too. If an organization is unresolved, use the person's name and documented role instead of inventing a company. Include a contradiction/correction/recency query. Prefer domain-restricted regulator and first-party searches. Do not assume LinkedIn can be fetched. No private data, login bypass, or outreach. State each query's purpose and preferred source type.`;
export const inputSchema = subjectInputSchema.extend({ queryBudget: z.number().int().min(8).max(12), querySeeds: z.array(z.string()).length(8) });
export const outputSchema = z.object({ queries: z.array(z.object({ query: z.string(), purpose: z.string(), preferredSourceType: sourceKindSchema,
  domainHint: z.string().nullable() })).min(8).max(12) });
